# Generated by Django 6.1.2 on 2026-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=False)),
            ],
        ),
    ]
